disabled_rules:
  - line_length

opt_in_rules:
  - force_unwrapping
  - anyobject_protocol
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - modifier_order
  - nimble_operator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - test_case_accessibility
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  
excluded:
  # Carthage でインストールしたライブラリは除外
  - Carthage

force_cast: warning

identifier_name:
  min_length: 1

type_name:
  max_length: 80
  excluded:
    - ID
  
large_tuple:
  warning: 3

nesting:
  type_level:
    warning: 3

inclusive_language:
  override_allowed_terms:
    - masterkeyword
    - masterkeywords
    - masterimage

cyclomatic_complexity:
  ignores_case_statements: true

function_body_length:
  warning: 80
  error: 200

type_body_length:
  warning: 400
  error: 750

file_length:
  warning: 800
  error: 2000
